### ISSUE TITLE
clash规则

### ISSUE THREAD

**Issue by updater1234** [lhie1/Rules#179]
为什么GEOIP,CN,后面接的是Domestic不应该是DIRECT吗?

**Comment by Chandler-Lu** [comment]
```
- name: Domestic
  type: select
  proxies:
  - DIRECT
  - Proxy
```
因为是个可选项- -你要是在国外也可以Proxy
