### ISSUE TITLE
clash规则如何使用？

### ISSUE THREAD

**Issue by luanwulin** [lhie1/Rules#189]
clash 规则中有很多 group，如GlobalTV和AdBlock是如何定义的呢？

**Comment by sh4d0wfiend** [comment]
An example of proxy groups for anyone interested:
```

Proxy Group:
  - name: Proxy
    type: select
    proxies:
      - your_proxies
  - name: Domestic
    type: select
    proxies:
      - DIRECT
      - Proxy
  - name: AdBlock
    type: select
    proxies:
      - REJECT
      - DIRECT
  - name: AsianTV
    type: select
    proxies:
      - Domestic
      - Proxy
  - name: GlobalTV
    type: select
    proxies:
      - Proxy
      - DIRECT
  - name: Apple
    type: select
    proxies:
      - DIRECT
      - Proxy
  - name: Microsoft
    type: select
    proxies:
      - DIRECT
      - Proxy
  - name: Telegram
    type: select
    proxies:
      - Proxy
      - DIRECT
  - name: Steam
    type: select
    proxies:
      - DIRECT
      - Proxy
  - name: Netease Music
    type: select
    proxies:
      - DIRECT
      - Proxy
  - name: Speedtest
    type: select
    proxies:
      - DIRECT
      - Proxy
  - name: Others
    type: select
    proxies:
      - Proxy
      - Domestic
```
